"use client";
//import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import React, { ReactNode } from "react";
import "./globals.scss";
import { Provider } from "react-redux";
import store from "state/store";
import RoutesProtection from "../components/routesProtection/routesProtection";
import { LoadScript } from "@react-google-maps/api";

//import { useSelector } from "react-redux";
//import { RootState } from "../state/store";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "700", "300", "400", "500"],
});

//No está permitido usar Metadata con useClient
/* export const metadata: Metadata = {
  title: "Box Delivery App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }: { children: ReactNode }) {
  // const user = useSelector((state: RootState) => state.user);

  return (
    <html lang="en">
      <Provider store={store}>
        <body className={`${roboto.className} body`}>
          <LoadScript
            googleMapsApiKey={process.env.NEXT_PUBLIC_API_GOOGLE_MAPS || ""}
            libraries={["places"]}
          >
            <RoutesProtection>{children}</RoutesProtection>
          </LoadScript>
        </body>
      </Provider>
    </html>
  );
}
